### ISSUE TITLE
Page flickers on load

### ISSUE THREAD

**Issue by qerub** [jorgerdz/lifxspace#1]
It takes a while for the page to stabilize on load with Angular templates showing and elements jumping around. It would be nice if the elements rendered correctly directly. Watch this example video in slow motion to see what I mean: http://cl.ly/0s2z1A410n3l

This seems relevant: https://stackoverflow.com/questions/17091364/avoiding-expressions-being-shown-on-page-load

**Comment by jorgerdz** [comment]
Hey, thanks for noticing. ng-cloak is definitely the solution, I'm surprised I hadn't implemented it previously. Will include in the next update.

**Comment by jorgerdz** [comment]
Fixed in latest commit https://github.com/jorgerdz/lifxspace/commit/2d1ebb493449431ec41543f2739b029f59d90882
